import { describe, expect, it } from "vitest";
import { exportProjectState } from "./project-serializer";

function createHost() {
    return {
        sceneModels: [],
        modelMotionImportsByModel: new WeakMap<object, unknown[]>(),
        modelSourceAnimationsByModel: new WeakMap<object, unknown>(),
        activeModelInfo: null,
        timelineTarget: "model",
        _currentFrame: 0,
        _playbackSpeed: 1,
        cameraMotionPath: null,
        audioSourcePath: null,
        camera: {
            position: { x: 0, y: 10, z: -30 },
            target: { x: 0, y: 10, z: 0 },
        },
        cameraRotationEulerDeg: { x: 0, y: 0, z: 0 },
        getCameraFov: (): number => 30,
        getCameraDistance: (): number => 30,
        getSerializedLightDirection: (): { _isDirty: boolean; _x: number; _y: number; _z: number; x: number; y: number; z: number } => ({
            _isDirty: true,
            _x: -0.64,
            _y: -0.65,
            _z: -0.35,
            x: -0.64,
            y: -0.65,
            z: -0.35,
        }),
        lightIntensity: 1,
        ambientIntensity: 0,
        lightColorTemperature: 6500,
        getLightColor: () => ({ r: 1, g: 1, b: 1 }),
        lightFlatStrength: 0,
        lightFlatColorInfluence: 0.35,
        getShadowColor: () => ({ r: 0.15, g: 0.15, b: 0.2 }),
        toonShadowInfluence: 1,
        shadowEnabled: true,
        shadowDarkness: 0,
        shadowFrustumSize: 220,
        shadowMaxZ: 4800,
        shadowBias: 0.0005,
        shadowNormalBias: 0.01,
        shadowEdgeSoftness: 0.03,
        selfShadowEdgeSoftness: 0.05,
        occlusionShadowEdgeSoftness: 0.01,
        isGroundVisible: (): boolean => true,
        isSkydomeVisible: (): boolean => true,
        antialiasEnabled: true,
        getBackgroundImagePath: (): null => null,
        getBackgroundVideoPath: (): null => null,
        physicsEnabled: true,
        physicsSimulationRateHz: 60,
        physicsGravityAcceleration: 98,
        physicsGravityDirection: { x: 0, y: -100, z: 0 },
        dofEnabled: false,
        dofFocusDistanceMm: 10000,
        dofAutoFocusNearOffsetMm: 0,
        getDofFocusTargetModelPath: (): null => null,
        getDofFocusTargetBoneName: (): null => null,
        dofBlurLevel: 1,
        dofFStop: 5.6,
        dofNearSuppressionScale: 4,
        dofLensSize: 50,
        dofFocalLength: 50,
        dofFocalLengthDistanceInverted: false,
        dofLensBlurStrength: 0,
        dofLensEdgeBlur: 0,
        dofLensDistortion: 0,
        dofLensDistortionInfluence: 0,
        modelEdgeWidth: 0,
        postEffectContrast: 1,
        postEffectGamma: 1,
        postEffectExposure: 1,
        postEffectToneMappingEnabled: false,
        postEffectToneMappingType: 0,
        postEffectDitheringEnabled: false,
        postEffectDitheringIntensity: 1 / 255,
        postEffectVignetteEnabled: false,
        postEffectVignetteWeight: 0.3,
        postEffectBloomEnabled: false,
        postEffectBloomWeight: 1,
        postEffectBloomThreshold: 1,
        postEffectBloomKernel: 100,
        postEffectChromaticAberration: 0,
        postEffectGrainIntensity: 0,
        postEffectSharpenEdge: 0,
        postEffectSsaoEnabled: false,
        postEffectSsaoStrength: 1,
        postEffectSsaoRadius: 2,
        postEffectSsaoFadeEnd: 200,
        postEffectSsaoDebugView: false,
        postEffectColorCurvesEnabled: false,
        postEffectColorCurvesHue: 30,
        postEffectColorCurvesDensity: 0,
        postEffectColorCurvesSaturation: 0,
        postEffectColorCurvesExposure: 0,
        postEffectGlowEnabled: false,
        postEffectGlowIntensity: 0.5,
        postEffectGlowKernel: 20,
        postEffectLutEnabled: false,
        postEffectLutIntensity: 1,
        postEffectLutPreset: "anime-soft",
        postEffectLutSourceMode: "builtin",
        getPostEffectExternalLutPath: (): null => null,
        getExternalWgslToonShaderPath: (): null => null,
        postEffectMotionBlurEnabled: false,
        postEffectMotionBlurStrength: 0.5,
        postEffectMotionBlurSamples: 32,
        postEffectSsrEnabled: false,
        postEffectSsrStrength: 0.8,
        postEffectSsrStep: 1,
        postEffectVlsEnabled: false,
        postEffectVlsExposure: 0.3,
        postEffectVlsDecay: 0.95,
        postEffectVlsWeight: 0.4,
        postEffectVlsDensity: 0.9,
        postEffectFogEnabled: false,
        postEffectFogMode: 2,
        postEffectFogStart: 100,
        postEffectFogEnd: 300,
        postEffectFogDensity: 0.002,
        postEffectFogOpacity: 0.2,
        getPostEffectFogColor: () => ({ r: 0.04, g: 0.04, b: 0.06 }),
        getModelVisibility: (): boolean => true,
        getSerializedMaterialShaderStates: (): [] => [],
        getLoadedAccessories: (): [] => [],
        cameraSourceAnimation: null,
    };
}

describe("exportProjectState", () => {
    it("writes light direction as x/y/z instead of Babylon backing fields", () => {
        const project = exportProjectState(createHost());

        expect(project.lighting.x).toBe(-0.64);
        expect(project.lighting.y).toBe(-0.65);
        expect(project.lighting.z).toBe(-0.35);
        expect("_x" in project.lighting).toBe(false);
        expect("_y" in project.lighting).toBe(false);
        expect("_z" in project.lighting).toBe(false);
    });
});
